### ISSUE TITLE
A bunch of warnings showing up after migrating to version 0.2.0

### ISSUE THREAD

**Issue by spaquet** [ruby/pathname#12]
Since upgrading to version 0.2.0 a lot of warning messages are popping up when launching an app or the console.

.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:20: warning: already initialized constant Pathname::TO_PATH
.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:20: warning: previous definition of TO_PATH was here
.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:22: warning: already initialized constant Pathname::SAME_PATHS
.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:22: warning: 
.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:34: warning: already initialized constant Pathname::SEPARATOR_LISTprevious definition of SEPARATOR_LIST was here
.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:35: warning: already initialized constant 
.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:35: warning: 
.rbenv/versions/3.0.1/lib/ruby/3.0.0/pathname.rb:41: warning: already initialized constant Pathname::ABSOLUTE_PATH previous definition of ABSOLUTE_PATH was here

Anybody else with the same warnings?

**Comment by deivid-rodriguez** [comment]
It sounds like it is going to be hard to get a repro, so here's some steps you can take to provide me with some more information about the issue:

* Find the entry points of the two copies of the library being involved here. For example:

```
$ fd pathname.rb$ ~/.rbenv/versions/3.0.2
/Users/deivid/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb
/Users/deivid/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb
```

* Open the files and add a debugging print to show a backtrace on top of each one. For example, by inserting:

```ruby
puts "=================================== backtrace =================================="
puts caller_locations(0).join("\n")
puts "================================================================================"
```

* Share the backtraces here.

**Comment by PanisSupraOmnia** [comment]
Before updating to v0.2.0 (so, just the default gem v0.1.0), there is only: `~/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb`.

After updating, we have the following:

```shell
~/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb
~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb
```

A diff of the two files:

```diff
~/.rbenv/versions/3.0.2/lib/ruby$ diff 3.0.0/pathname.rb gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb 
577a578,579
>   autoload(:FileUtils, 'fileutils')
> 
582,584c584,585
<   def mkpath
<     require 'fileutils'
<     FileUtils.mkpath(@path)
---
>   def mkpath(mode: nil)
>     FileUtils.mkpath(@path, mode: mode)
594d594
<     require 'fileutils'
```

A plain IRB session (no bundler) gives no warnings:

```ruby
irb(main):001:0> require 'pathname'
=> true
```

If IRB is started by creating a new, basic gem with `bundle gem` and running either `bundle exec irb` or `bundle console`, it will print the warnings, and upon exiting IRB there is a segfault. I've uploaded a gist with the coredumps for these two cases [here](https://gist.github.com/PanisSupraOmnia/c2bbeb75644185d3f2cb5137b5a61abe).

If I use the `bin/console` binstub that bundler creates when generating the gem, the same warnings still print. However, the segfault does NOT occur upon exiting IRB.

Even if I add IRB to the bundle, generate a binstub for IRB, and `require 'pathname'` the same way as before, the warnings print but there is no segfault. Adding other gems and running the generated binstubs for those such as `bin/rubocop` will cause the segfault however.

I realize I haven't found the exact issue yet, but I'll keep digging later; hopefully what I've found so far can be of use.

**Comment by deivid-rodriguez** [comment]
A segfault is surprising and it should probably be reported to ruby-core.

Regarding the warning, can you show a backtrace of the require point of each file (write the snippet above into each of the involved `pathname.rb` files and share the output).

**Comment by PanisSupraOmnia** [comment]
Oh oops, I didn't read your comment right at first, so I didn't realize you wanted the backtrace lines inserted into the actual lib files, my bad. Otherwise, I would have included that in my first reply. [Here's another gist](https://gist.github.com/PanisSupraOmnia/6716adbf75521dc2a1338b83c0ed6c38) with the backtraces on; I've also included the outputs of `gem env` there, as well as `bundle env` for the basic gem I used in the examples that used bundler. Let me know if there's anything else I can do to help!

**Comment by deivid-rodriguez** [comment]
Oh, I see what the problem is now.

When `bundler/setup` is required, some relevant things happen in the following order:

* [`pathname` is required by bundler](https://github.com/rubygems/rubygems/blob/c9f072a3b353985aa932796d8d34d37134005ed8/bundler/lib/bundler.rb#L4), and the `pathname` gem is activated, because `rubygems` require is in place here, and it automatically activates the highest version of default gems present in the system. In this case, pathname 0.2.0 is activated.

* Then, in order to setup the load path to only include gems specified in the Gemfile, bundler first [cleans paths from activated gems from the `$LOAD_PATH`](https://github.com/rubygems/rubygems/blob/c9f072a3b353985aa932796d8d34d37134005ed8/bundler/lib/bundler/runtime.rb#L16), removing `~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib` from it. 

* Then bundler ["unmonkeypatches" rubygems `require`](https://github.com/rubygems/rubygems/blob/c9f072a3b353985aa932796d8d34d37134005ed8/bundler/lib/bundler/runtime.rb#L21) going back ruby's default `require` which only searches the `$LOAD_PATH` without any extra magic to activate gems, because we know the exact paths of all gems that we need (the ones in the `Gemfile{,.lock}`).

* Finally bundler [puts the paths of the exact set of gems specified in the `Gemfile{,.lock}`into the `$LOAD_PATH`](https://github.com/rubygems/rubygems/blob/c9f072a3b353985aa932796d8d34d37134005ed8/bundler/lib/bundler/runtime.rb#L31).

As a consequence, by the time `pathname` is required the second time, the `$LOAD_PATH` no longer includes `~/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib` and ruby's default `require` is used this time, resulting in the default version of `pathname` (`~/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb`) being loaded this time, and the redefinition warnings triggered.

We need to refactor `bundler` internals to not require `pathname` so early, and but doing that we'll fix this issue, but also add support for `pathname` to be specified in the `Gemfile`, which is [not yet supported](https://github.com/rubygems/rubygems/blob/c9f072a3b353985aa932796d8d34d37134005ed8/bundler/spec/runtime/setup_spec.rb#L1264).

I'll work on this tomorrow.

**Comment by tarragon** [comment]
Hi!

I'm seeing a lot of similar warnings (including pathname), is https://github.com/ruby/pathname/issues/12#issuecomment-945198245 likely to be the cause?

Examples (truncated for brevity):

```
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/uri/version.rb:3: warning: already initialized constant URI::VERSION_CODE
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/uri-0.11.0/lib/uri/version.rb:3: warning: previous definition of VERSION_CODE was here
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/uri/version.rb:4: warning: already initialized constant URI::VERSION
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/uri-0.11.0/lib/uri/version.rb:4: warning: previous definition of VERSION was here

/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/uri/rfc2396_parser.rb:28: warning: already initialized constant URI::RFC2396_REGEXP::PATTERN::ALPHA
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/uri-0.11.0/lib/uri/rfc2396_parser.rb:28: warning: previous definition of ALPHA was here
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/uri/rfc2396_parser.rb:30: warning: already initialized constant URI::RFC2396_REGEXP::PATTERN::ALNUM
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/uri-0.11.0/lib/uri/rfc2396_parser.rb:30: warning: previous definition of ALNUM was here

/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/uri-0.11.0/lib/uri/rfc3986_parser.rb:7: warning: previous definition of RFC3986_relative_ref was here
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/uri/common.rb:16: warning: already initialized constant URI::REGEXP
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/uri-0.11.0/lib/uri/common.rb:16: warning: previous definition of REGEXP was here
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/uri/common.rb:17: warning: already initialized constant URI::Parser

/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:20: warning: already initialized constant Pathname::TO_PATH
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:20: warning: previous definition of TO_PATH was here
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:22: warning: already initialized constant Pathname::SAME_PATHS
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/pathname-0.2.0/lib/pathname.rb:22: warning: previous definition of SAME_PATHS was here
/Users/tarragon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pathname.rb:34: warning: already initialized constant Pathname::SEPARATOR_LIST
```

**Comment by deivid-rodriguez** [comment]
The underlying cause is the same: a new version of default gems used by bundler/rubygems internally has been released (in this case, uri-0.11.0), potentially causing two versions of the same gem to be activated at the same time. Solution is also to vendor `uri` inside bundler/rubygems.

**Comment by brettcurtis** [comment]
I'm trying to run kitchen tests and I segfault with pathname-0.2.0.

```none
/home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/shared_helpers.rb:58: [BUG] Segmentation fault at 0x0000000000000008
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
```

If I `gem uninstall pathname` my kitchen test run with pathname-0.1.0 however I see all the warning messages as the OP mentions.

I'm running on a fresh WSL2 ubuntu install setting up my env like so:

```bash
# Ruby
brew install ruby
echo 'export RUBYOPT="-W:no-deprecated -W:no-experimental"' >> ~/.zshrc
echo 'gem: --no-document' > ~/.gemrc
cat << EOF > ~/Gemfile
source "https://rubygems.org/"
  
source "https://rubygems.org/" do
    gem "kitchen-terraform"
    gem "inspec"
    gem "inspec-bin"
    gem "rubocop"
    gem "cookstyle"
end
EOF

echo 'export BUNDLE_GEMFILE="~/Gemfile"' >> ~/.zshrc

source ~/.zshrc

gem install bundle
gem update
bundle update
```

If this is a problem outside the scope of this repo and my info may be useful, can you point me to the correct place?

**Comment by hsbt** [comment]
@brettcurtis Please separate your SEGV issues from this? It seems to the difference.

**Comment by brettcurtis** [comment]
@hsbt - done! https://github.com/ruby/pathname/issues/14

**Comment by deivid-rodriguez** [comment]
Can someone having this issue (or #14, I believe it's the same after all) verify that this little patch to bundler fixes things:

```diff
diff --git a/bundler/lib/bundler/shared_helpers.rb b/bundler/lib/bundler/shared_helpers.rb
index 405ade95dd..846b9cc3aa 100644
--- a/bundler/lib/bundler/shared_helpers.rb
+++ b/bundler/lib/bundler/shared_helpers.rb
@@ -313,12 +313,11 @@ def bundler_ruby_lib
     end
 
     def clean_load_path
-      bundler_lib = bundler_ruby_lib
-
       loaded_gem_paths = Bundler.rubygems.loaded_gem_paths
 
       $LOAD_PATH.reject! do |p|
-        next if resolve_path(p).start_with?(bundler_lib)
+        resolved_path = resolve_path(p)
+        next if $LOADED_FEATURES.any? {|lf| lf.start_with?(resolved_path) }
         loaded_gem_paths.delete(p)
       end
       $LOAD_PATH.uniq!
```

**Comment by brettcurtis** [comment]
@deivid-rodriguez - I'm back in business with that patch - Thanks !

**Comment by deivid-rodriguez** [comment]
Bundler 2.2.33 has been released which I expect to fix this issue. I think this can be closed.

**Comment by brettcurtis** [comment]
"Works on my Laptop" :D Thanks for the fix!

**Comment by cmirnow** [comment]
> Bundler 2.2.33 has been released which I expect to fix this issue. I think this can be closed.

`bundle update --bundler`

Great! Thanks for this fix!

**Comment by mattstone** [comment]
Updating bundler fixed this for me. Thanks for the fix.
